### PR TITLE
New atomix ref

### PR DESCRIPTION
**Pull request by breathbath**

### CODE REVIEW

**Review by Andrea-Campanella — APPROVED** [review]

**Review by hwchiu — APPROVED** [review]
LGTM

**Comment by Andrea-Campanella** [comment]
@hwchiu what is the missing check in Aether ?

**Comment by hwchiu** [comment]
retest this please

**Comment by tomikazi** [comment]
What's the status of this? Is it still relevant?

**Comment by teone** [comment]
I don't see any file changed so don't think so

**Pull request closed without merging**
