### PR TITLE
Passing java_opts as parameter from values.yaml

### PR DESCRIPTION
**Pull request by Andrea-Campanella**
This change allows passing of java_opts environment variable to the container through the values files, allowing for easy tuning of java parameters that ONOS uses to run

### CODE REVIEW

**Review by pierventre — CHANGES_REQUESTED** [review]
You need to update the reqs in order to get my change.

**Comment by pierventre** [comment]
@charlesmcchan @kuujo

**Comment by Andrea-Campanella** [comment]
@pierventre updatet to `0.1.4` please check

**Review by pierventre — APPROVED** [review]
On hold waiting for the Atomix pr

**Review by charlesmcchan — APPROVED** [review]

**Review by pierventre — APPROVED** [review]

**Pull request merged**
