### PR TITLE
Update topo config to entities

### PR DESCRIPTION
**Pull request by shadansari**

### CODE REVIEW

**Comment by shadansari** [comment]
@adibrastegarnia - this is not a fix for the helmit/integration test failing. This is regarding the post-install topo config that is loaded by the onos-umbrella chart. I had made the changes to sd-ran chart (https://github.com/onosproject/sdran-helm-charts/commit/11f8bffd43e2780dd949b4327c9b253277bfa209) but had missed out updating the onos-umbrella chart.

**Comment by adibrastegarnia** [comment]
@shadansari 
OK. Since you are making the required changes in those files to make them usable, please make sure you can add one of those devices using topo API and onos-config can detect it. Perhaps you need to change port number and device names based on device simulator helm chart. It adds "device-simulator" to the name of deployment and service: 
https://github.com/onosproject/onos-helm-charts/blob/master/device-simulator/templates/deployment.yaml#L4
https://github.com/onosproject/onos-helm-charts/blob/master/device-simulator/values.yaml#L23

**Comment by shadansari** [comment]
@adibrastegarnia - I have tested by bringing up the onos-umbrella chart and verifying from the cli that entities loaded by the post-install job are seen in the cli:

'''
$ onos topo get entities
Object Type     Object ID       Kind ID         Attributes
ENTITY          sample-2        Devicesim       plmnid:, grpcport:, arc:, address:sample-2:0, version:1.0.0, azimuth:, longitude:13.3885, ecid:, tls-insecure:true, latitude:52.5350, displayname:Other sample device
ENTITY          devicesim-1     Devicesim       grpcport:5150, latitude:52.5150, address:devicesim-1:5150, arc:, displayname:Device Sim 1, version:1.0.0, ecid:, tls-insecure:true, plmnid:, longitude:13.3885, azimuth:
ENTITY          devicesim-2     Devicesim       address:devicesim-2:5150, version:1.0.0, plmnid:, longitude:13.4215, azimuth:, displayname:Device Sim 2, grpcport:5150, tls-insecure:true, arc:, latitude:52.5150, ecid:
ENTITY          sample-1        TestDevice      azimuth:, version:1.0.0, plmnid:, tls-insecure:true, displayname:Sample device, ecid:, arc:, longitude:13.3885, latitude:52.5350, grpcport:, address:sample-1:0
'''

**Comment by adibrastegarnia** [comment]
@shadansari 
Perhaps I didn't explain it well. 
I mean can you add a device simulator which matches one of those devices? If we cannot add a device simulator which matches with those device simulators then we cannot use those entries. I would suggest to add a device simulator using its helm chart and check its name and port number that it listens to.

**Comment by shadansari** [comment]
@adibrastegarnia - I can see the devices in topo __and__ config - which means the device simulator is loaded by onos-config (I dont know how):


~ $ onos topo get entities
Object Type     Object ID       Kind ID         Attributes
ENTITY          devicesim-1     Devicesim       grpcport:5150, tls-insecure:true, address:devicesim-1:5150, displayname:Device Sim 1, version:1.0.0, arc:, latitude:52.5150, plmnid:, ecid:, azimuth:, longitude:13.3885
ENTITY          devicesim-2     Devicesim       azimuth:, address:devicesim-2:5150, ecid:, displayname:Device Sim 2, longitude:13.4215, arc:, latitude:52.5150, grpcport:5150, plmnid:, version:1.0.0, tls-insecure:true

~ $ onos config get device-changes devicesim-1
CHANGE                          INDEX  REVISION  PHASE    STATE     REASON   MESSAGE
amazing_hopper:devicesim-1:1.0.0 1       38       CHANGE   PENDING   NONE
	amazing_hopper	1	devicesim-1	1.0.0
	|/system/clock/config/timezone-name                |(STRING) Europe/Berlin                  |false  |
	|/system/config/motd-banner                        |(STRING) Welcome to Device Sim 1        |false  |

~ $ onos config get device-changes devicesim-2
CHANGE                          INDEX  REVISION  PHASE    STATE     REASON   MESSAGE
mystifying_napier:devicesim-2:1.0.0 2       46       CHANGE   PENDING   NONE
	mystifying_napier	2	devicesim-2	1.0.0
	|/system/clock/config/timezone-name                |(STRING) Europe/Paris                   |false  |
	|/system/config/motd-banner                        |(STRING) Welcome to Device Sim 1        |false  |

**Comment by adibrastegarnia** [comment]
@shadansari 
Do we have onos topo get devices anymore or it is replaced with onos topo get entities? When we add a device simulator (using helm), onos-config listens to topology changes and make a connection to the device. If everything is OK then you should be able to see in logs onos-config is connected to that device successfully (onos topo get devices shows the state of a device) otherwise it keeps retrying to connect to that device. Keep in mind that onos-umbrella chart doesn't deploy a device simulator by default.

**Comment by shadansari** [comment]
@adibrastegarnia - this is perhaps the longest comments trail I ever entertained :) 

1) onos-config is loading something called Devicesim and TestDevice models.
2) Please go through the onos-config logs below and verify. I dont know as much about internals onos-config as you so please let me know if you see an issue.


```
➜  onos-helm-charts git:(onos-topo-config) kubectl -n micro-onos logs onos-config-549d5d4687-qbzst
error: a container name must be specified for pod onos-config-549d5d4687-qbzst, choose one of: [onos-config config-model-devicesim-1-0-0 config-model-testdevice-1-0-0 config-model-testdevice-2-0-0]
➜  onos-helm-charts git:(onos-topo-config) kubectl -n micro-onos logs onos-config-549d5d4687-qbzst -c onos-config
2020-08-05T00:36:01.483Z	INFO	main	onos-config/onos-config.go:95	Starting onos-config
2020-08-05T00:36:01.604Z	INFO	main	onos-config/onos-config.go:136	Topology service connected with endpoint onos-topo:5150
2020-08-05T00:36:01.604Z	INFO	main	onos-config/onos-config.go:138	Network Configuration store connected
2020-08-05T00:36:01.606Z	INFO	main	onos-config/onos-config.go:149	Topology service connected with endpoint onos-topo:5150
2020-08-05T00:36:01.606Z	INFO	manager	manager/manager.go:84	Creating Manager
2020-08-05T00:36:01.606Z	INFO	main	onos-config/onos-config.go:154	Manager started
2020-08-05T00:36:01.607Z	INFO	modelregistry	modelregistry/modelregistry.go:162	Loading module /usr/local/lib/shared/devicesim.so.1.0.0
2020-08-05T00:36:01.744Z	INFO	modelregistry	modelregistry/modelregistry.go:227	**Model Devicesim 1.0.0 loaded**. 37 read only paths. 113 read write paths
2020-08-05T00:36:01.744Z	INFO	modelregistry	modelregistry/modelregistry.go:162	Loading module /usr/local/lib/shared/testdevice.so.1.0.0
2020-08-05T00:36:01.774Z	INFO	modelregistry	modelregistry/modelregistry.go:227	**Model TestDevice 1.0.0 loaded**. 2 read only paths. 10 read write paths
2020-08-05T00:36:01.774Z	INFO	modelregistry	modelregistry/modelregistry.go:162	Loading module /usr/local/lib/shared/testdevice.so.2.0.0
2020-08-05T00:36:01.798Z	INFO	modelregistry	modelregistry/modelregistry.go:227	Model TestDevice 2.0.0 loaded. 2 read only paths. 15 read write paths
2020-08-05T00:36:01.798Z	INFO	manager	manager/manager.go:123	Starting Manager
2020-08-05T00:36:01.799Z	INFO	dispatcher	dispatcher/dispatcher.go:54	Operational State Event listener initialized
2020-08-05T00:36:01.799Z	INFO	controller	controller/controller.go:143	Activating controller NetworkSnapshot
2020-08-05T00:36:01.799Z	INFO	manager	manager/manager.go:159	Manager Started
2020-08-05T00:36:01.799Z	INFO	controller	controller/controller.go:143	Activating controller NetworkChange
2020-08-05T00:36:01.799Z	INFO	controller	controller/controller.go:143	Activating controller DeviceChange
2020-08-05T00:36:01.799Z	INFO	controller	controller/controller.go:143	Activating controller DeviceSnapshot
2020-08-05T00:36:01.799Z	INFO	manager	manager/manager.go:176	Listening for Errors in Manager
2020-08-05T00:36:01.800Z	INFO	controller/change/network	network/watcher.go:137	Network DeviceWatcher - watching cache started 0xc00009ed20
2020-08-05T00:36:01.800Z	INFO	northbound	northbound/server.go:119	Loading certs: /etc/onos/certs/tls.crt /etc/onos/certs/tls.key
2020-08-05T00:36:01.802Z	INFO	main	onos-config/onos-config.go:192	Started NBI on [::]:5150
2020-08-05T00:36:01.803Z	INFO	northbound	northbound/server.go:164	Starting RPC server on address: [::]:5150
2020-08-05T00:36:22.719Z	INFO	northbound/gnmi	gnmi/set.go:55	gNMI Set Requestprefix:<target:"devicesim-1" > update:<path:<elem:<name:"system" > elem:<name:"clock" > elem:<name:"config" > elem:<name:"timezone-name" > > val:<string_val:"Europe/Berlin" > > update:<path:<elem:<name:"system" > elem:<name:"config" > elem:<name:"motd-banner" > > val:<string_val:"Welcome to Device Sim 1" > > extension:<registered_ext:<id:101 msg:"1.0.0" > > extension:<registered_ext:<id:102 msg:"Devicesim" > >
2020-08-05T00:36:22.719Z	INFO	northbound/gnmi	gnmi/set.go:244	Set called with extensions; 100: , 101: 1.0.0, 102:
2020-08-05T00:36:22.719Z	INFO	northbound/gnmi	gnmi/set.go:244	Set called with extensions; 100: , 101: 1.0.0, 102: Devicesim
2020-08-05T00:36:22.721Z	INFO	manager	manager/manager.go:245	Device devicesim-1 not found in topo store
2020-08-05T00:36:22.721Z	INFO	northbound/gnmi	gnmi/set.go:399	Validating change devicesim-1:Devicesim:1.0.0
2020-08-05T00:36:22.727Z	INFO	manager	manager/setconfig.go:93	New Configuration for devicesim-1, with version 1.0.0 and type Devicesim, is Valid according to model Devicesim-1.0.0
2020-08-05T00:36:22.727Z	INFO	northbound/gnmi	gnmi/set.go:407	Validating change devicesim-1:Devicesim:1.0.0 DONE
2020-08-05T00:36:22.727Z	INFO	northbound/gnmi	gnmi/set.go:354	Testing /system/clock/config/timezone-name for read only
2020-08-05T00:36:22.727Z	INFO	northbound/gnmi	gnmi/set.go:354	Testing /system/config/motd-banner for read only
2020-08-05T00:36:22.727Z	INFO	manager	manager/setconfig.go:135	Appending device change device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > >
2020-08-05T00:36:22.729Z	INFO	store/device/cache	cache/cache.go:132	Updating cache with {devicesim-1 Devicesim 1.0.0}. Size 1 Listeners 2
2020-08-05T00:36:22.729Z	INFO	controller/change/network	network/watcher.go:115	Received device event for device devicesim-1 1.0.0
2020-08-05T00:36:22.729Z	INFO	controller/change/device	device/watcher.go:59	Received device event for device devicesim-1 1.0.0
2020-08-05T00:36:22.732Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"amazing_hopper" index:1 revision:35 status:<> created:<seconds:1596587782 nanos:728396600 > updated:<seconds:1596587782 nanos:728396600 > changes:<device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > >
2020-08-05T00:36:22.733Z	INFO	northbound/gnmi	gnmi/set.go:55	gNMI Set Requestprefix:<elem:<name:"system" > target:"devicesim-2" > update:<path:<elem:<name:"clock" > elem:<name:"config" > elem:<name:"timezone-name" > > val:<string_val:"Europe/Paris" > > update:<path:<elem:<name:"config" > elem:<name:"motd-banner" > > val:<string_val:"Welcome to Device Sim 1" > > extension:<registered_ext:<id:101 msg:"1.0.0" > > extension:<registered_ext:<id:102 msg:"Devicesim" > >
2020-08-05T00:36:22.733Z	INFO	northbound/gnmi	gnmi/set.go:244	Set called with extensions; 100: , 101: 1.0.0, 102:
2020-08-05T00:36:22.733Z	INFO	northbound/gnmi	gnmi/set.go:244	Set called with extensions; 100: , 101: 1.0.0, 102: Devicesim
2020-08-05T00:36:22.738Z	INFO	controller/change/network	network/controller.go:199	Creating DeviceChange index:1 network_change:<id:"amazing_hopper" index:1 > change:<device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > status:<> created:<seconds:-62135596800 > updated:<seconds:-62135596800 >  for amazing_hopper
2020-08-05T00:36:22.739Z	ERROR	controller/change/network	network/watcher.go:118	Could not find device devicesim-1
github.com/onosproject/onos-lib-go/pkg/logging.(*zapOutput).Errorf
	/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/output.go:196
github.com/onosproject/onos-lib-go/pkg/logging.(*zapLogger).Errorf
	/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/logger.go:276
github.com/onosproject/onos-config/pkg/controller/change/network.(*DeviceWatcher).Start.func2
	/go/src/github.com/onosproject/onos-config/pkg/controller/change/network/watcher.go:118
2020-08-05T00:36:22.740Z	INFO	store/change/device	device/store.go:237	Created new device change amazing_hopper:devicesim-1:1.0.0
2020-08-05T00:36:22.742Z	INFO	manager	manager/manager.go:245	Device devicesim-2 not found in topo store
2020-08-05T00:36:22.742Z	INFO	northbound/gnmi	gnmi/set.go:399	Validating change devicesim-2:Devicesim:1.0.0
2020-08-05T00:36:22.745Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"amazing_hopper" index:1 revision:40 status:<> created:<seconds:1596587782 nanos:728396600 > updated:<seconds:1596587782 nanos:741495700 > changes:<device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > refs:<device_change_id:"amazing_hopper:devicesim-1:1.0.0" >
2020-08-05T00:36:22.745Z	INFO	controller/change/device	device/controller.go:82	Reconciling DeviceChange id:"amazing_hopper:devicesim-1:1.0.0" index:1 revision:38 network_change:<id:"amazing_hopper" index:1 > change:<device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > status:<> created:<seconds:1596587782 nanos:739800300 > updated:<seconds:1596587782 nanos:739800300 >
2020-08-05T00:36:22.746Z	INFO	manager	manager/setconfig.go:93	New Configuration for devicesim-2, with version 1.0.0 and type Devicesim, is Valid according to model Devicesim-1.0.0
2020-08-05T00:36:22.746Z	INFO	northbound/gnmi	gnmi/set.go:407	Validating change devicesim-2:Devicesim:1.0.0 DONE
2020-08-05T00:36:22.746Z	INFO	northbound/gnmi	gnmi/set.go:354	Testing /system/clock/config/timezone-name for read only
2020-08-05T00:36:22.746Z	INFO	northbound/gnmi	gnmi/set.go:354	Testing /system/config/motd-banner for read only
2020-08-05T00:36:22.748Z	INFO	manager	manager/setconfig.go:135	Appending device change device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > >
2020-08-05T00:36:22.748Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"amazing_hopper" index:1 revision:40 status:<> created:<seconds:1596587782 nanos:728396600 > updated:<seconds:1596587782 nanos:741495700 > changes:<device_id:"devicesim-1" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Berlin" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > refs:<device_change_id:"amazing_hopper:devicesim-1:1.0.0" >
2020-08-05T00:36:22.749Z	INFO	store/device/cache	cache/cache.go:132	Updating cache with {devicesim-2 Devicesim 1.0.0}. Size 2 Listeners 2
2020-08-05T00:36:22.749Z	INFO	controller/change/device	device/watcher.go:59	Received device event for device devicesim-2 1.0.0
2020-08-05T00:36:22.749Z	INFO	controller/change/network	network/watcher.go:115	Received device event for device devicesim-2 1.0.0
2020-08-05T00:36:22.753Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"mystifying_napier" index:2 revision:43 status:<> created:<seconds:1596587782 nanos:749015800 > updated:<seconds:1596587782 nanos:749015800 > changes:<device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > >
2020-08-05T00:36:22.753Z	INFO	controller/change/network	network/controller.go:199	Creating DeviceChange index:2 network_change:<id:"mystifying_napier" index:2 > change:<device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > status:<> created:<seconds:-62135596800 > updated:<seconds:-62135596800 >  for mystifying_napier
2020-08-05T00:36:22.753Z	ERROR	controller/change/network	network/watcher.go:118	Could not find device devicesim-2
github.com/onosproject/onos-lib-go/pkg/logging.(*zapOutput).Errorf
	/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/output.go:196
github.com/onosproject/onos-lib-go/pkg/logging.(*zapLogger).Errorf
	/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/logger.go:276
github.com/onosproject/onos-config/pkg/controller/change/network.(*DeviceWatcher).Start.func2
	/go/src/github.com/onosproject/onos-config/pkg/controller/change/network/watcher.go:118
2020-08-05T00:36:22.755Z	INFO	store/change/device	device/store.go:237	Created new device change mystifying_napier:devicesim-2:1.0.0
2020-08-05T00:36:22.757Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"mystifying_napier" index:2 revision:47 status:<> created:<seconds:1596587782 nanos:749015800 > updated:<seconds:1596587782 nanos:755511600 > changes:<device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > refs:<device_change_id:"mystifying_napier:devicesim-2:1.0.0" >
2020-08-05T00:36:22.759Z	INFO	controller/change/device	device/controller.go:82	Reconciling DeviceChange id:"mystifying_napier:devicesim-2:1.0.0" index:2 revision:46 network_change:<id:"mystifying_napier" index:2 > change:<device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > status:<> created:<seconds:1596587782 nanos:754663300 > updated:<seconds:1596587782 nanos:754663300 >
2020-08-05T00:36:22.760Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"mystifying_napier" index:2 revision:47 status:<> created:<seconds:1596587782 nanos:749015800 > updated:<seconds:1596587782 nanos:755511600 > changes:<device_id:"devicesim-2" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/system/clock/config/timezone-name" value:<bytes:"Europe/Paris" type:STRING > > values:<path:"/system/config/motd-banner" value:<bytes:"Welcome to Device Sim 1" type:STRING > > > refs:<device_change_id:"mystifying_napier:devicesim-2:1.0.0" >
2020-08-05T00:37:47.490Z	INFO	northbound/diags	diags/diags.go:218	ListDeviceChanges called with devicesim-1 . Subscribe false
2020-08-05T00:37:47.492Z	INFO	manager	manager/manager.go:245	Device devicesim-1 not found in topo store
2020-08-05T00:37:47.492Z	INFO	manager	manager/manager.go:259	Handling target devicesim-1 as :
2020-08-05T00:37:47.492Z	INFO	manager	manager/manager.go:261	Ignoring device type  and version  from extension for devicesim-1. Using Devicesim and 1.0.0
2020-08-05T00:37:47.493Z	INFO	northbound/diags	diags/diags.go:291	Sending matching change amazing_hopper:devicesim-1:1.0.0
2020-08-05T00:37:47.493Z	INFO	northbound/diags	diags/diags.go:306	Closing ListDeviceChanges for devicesim-1
2020-08-05T00:38:05.048Z	INFO	northbound/diags	diags/diags.go:124	ListNetworkChanges called with devicesim-1. Subscribe false
2020-08-05T00:38:05.050Z	INFO	northbound/diags	diags/diags.go:212	Closing ListNetworkChanges for devicesim-1
2020-08-05T00:38:39.571Z	INFO	northbound/diags	diags/diags.go:218	ListDeviceChanges called with devicesim-1 . Subscribe false
2020-08-05T00:38:39.574Z	INFO	manager	manager/manager.go:245	Device devicesim-1 not found in topo store
2020-08-05T00:38:39.574Z	INFO	manager	manager/manager.go:259	Handling target devicesim-1 as :
2020-08-05T00:38:39.574Z	INFO	manager	manager/manager.go:261	Ignoring device type  and version  from extension for devicesim-1. Using Devicesim and 1.0.0
2020-08-05T00:38:39.576Z	INFO	northbound/diags	diags/diags.go:291	Sending matching change amazing_hopper:devicesim-1:1.0.0
2020-08-05T00:38:39.576Z	INFO	northbound/diags	diags/diags.go:306	Closing ListDeviceChanges for devicesim-1
2020-08-05T00:38:41.224Z	INFO	northbound/diags	diags/diags.go:218	ListDeviceChanges called with devicesim-2 . Subscribe false
2020-08-05T00:38:41.227Z	INFO	manager	manager/manager.go:245	Device devicesim-2 not found in topo store
2020-08-05T00:38:41.227Z	INFO	manager	manager/manager.go:259	Handling target devicesim-2 as :
2020-08-05T00:38:41.227Z	INFO	manager	manager/manager.go:261	Ignoring device type  and version  from extension for devicesim-2. Using Devicesim and 1.0.0
2020-08-05T00:38:41.229Z	INFO	northbound/diags	diags/diags.go:291	Sending matching change mystifying_napier:devicesim-2:1.0.0
2020-08-05T00:38:41.229Z	INFO	northbound/diags	diags/diags.go:306	Closing ListDeviceChanges for devicesim-2
➜  onos-helm-charts git:(onos-topo-config)
```

**Comment by adibrastegarnia** [comment]
Will address the name and port number of the simulator later

**Comment by shadansari** [comment]
See https://github.com/onosproject/onos-helm-charts/issues/169

**Pull request merged**
