### PR TITLE
Update tost

### PR DESCRIPTION
**Pull request by pierventre**
Update tost-onos dependency

### CODE REVIEW

**Comment by pierventre** [comment]
@charlesmcchan @hwchiu once we merge this we need to pull again the atomix image in all the deployments. Sorry, it was my bad.

**Comment by charlesmcchan** [comment]
> @charlesmcchan @hwchiu once we merge this we need to pull again the atomix image in all the deployments. Sorry, it was my bad.

Sorry I didn't get it. Why do we need to pull Atomix images again?

**Comment by pierventre** [comment]
When we added the support for the java_opts - we had just to re-run the docker build using the latest openjdk8 image as base. However I have not done a formal release with a new tag.

**Review by charlesmcchan — APPROVED** [review]

**Comment by charlesmcchan** [comment]
Jenkins failed since this PR attempted to change both `onos-classic` and `onos-tost`. @hwchiu has split this into two patches (#223, #224). I am going to close this PR.

**Comment by pierventre** [comment]
This patch needed  a rebase once we merge #219. It has been done on purpose on that way...

**Pull request closed without merging**
