### PR TITLE
Feature/onos config loader

### PR DESCRIPTION
**Pull request by teone**
Implementation for https://jira.opennetworking.org/browse/SDFAB-198

Unifies `sd-fabric` and `voltha` methodologies to load configuration in ONOS

### CODE REVIEW

**Comment by teone** [comment]
This has been tested in the VOLTHA ecosystem and is working as expected, can be merged anytime on our side.

**Review by Andrea-Campanella — APPROVED** [review]

**Comment by hwchiu** [comment]
@teone sounds good, it's been tested from the SD-Fabric side as well, let merge it and report any issue to me if you see anything.

**Comment by Andrea-Campanella** [comment]
@hwchiu are you going to merge or should I ?

**Comment by hwchiu** [comment]
Thanks for the help !

**Pull request merged**
