### PR TITLE
AETHER-2600: Add PSP to onos-classic chart

### PR DESCRIPTION
**Pull request by frouzbeh**
@hyunsun Please review this.
Thanks

### CODE REVIEW

**Review by teone — APPROVED** [review]
@frouzbeh look good to me and being disabled by default won't affect VOLTHA. Ok to merge anytime.

**Comment by teone** [comment]
@pierventre @charlesmcchan @hwchiu do you have any issue with this?

**Comment by frouzbeh** [comment]
@teone Thanks, I'm not authorized to merge in this repo, please merge it whenever it's possible. Thanks

**Review by pierventre — APPROVED** [review]
No concerns

**Comment by teone** [comment]
@frouzbeh merged

**Pull request merged**
