### PR TITLE
Update karaf version

### PR DESCRIPTION
**Pull request by pierventre**

### CODE REVIEW

**Review by charlesmcchan — APPROVED** [review]
Please also check aether-app-config / aether-pod-config and see if this value is overridden in value files. If someone is using master image with old value it might create some errors.

**Comment by pierventre** [comment]
> Please also check aether-app-config / aether-pod-config and see if this value is overridden in value files. If someone is using master image with old value it might create some errors.

done

**Comment by pierventre** [comment]
@charlesmcchan can you merge this ? I don't have power

**Comment by Andrea-Campanella** [comment]
done @pierventre

**Pull request merged**
