### PR TITLE
Resource limits

### PR DESCRIPTION
**Pull request by breathbath**

### CODE REVIEW

**Review by Andrea-Campanella — APPROVED** [review]
LGTM and to the VOLTHA team

**Review by hwchiu — APPROVED** [review]
LGTM and SDFabric team.

**Review by hwchiu — CHANGES_REQUESTED** [review]
Please bump helm chart version as well (Chart.yaml).

**Comment by breathbath** [comment]
Done

**Review by hwchiu — APPROVED** [review]
LGTM, thanks

**Comment by Andrea-Campanella** [comment]
@hwchiu can you merge when Aether Jenkins verifies ?

**Comment by hwchiu** [comment]
> @hwchiu can you merge when Aether Jenkins verifies ?

Of course, I can do it.

**Comment by ray-milkey** [comment]
retest this please

**Pull request merged**
